// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG7VTiaAgG7ZUrGd9Mn9wiMbatwVUh2ZQ',
    appId: '1:140191368992:web:1c5fbb238f719a0ed17945',
    messagingSenderId: '140191368992',
    projectId: 'ya-perfume',
    authDomain: 'ya-perfume.firebaseapp.com',
    storageBucket: 'ya-perfume.firebasestorage.app',
    measurementId: 'G-3KNPSD4L2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO-ZupL8qZCSGF2rqAyDNZdSa0TtvBi90',
    appId: '1:140191368992:android:72d64075a3de67fed17945',
    messagingSenderId: '140191368992',
    projectId: 'ya-perfume',
    storageBucket: 'ya-perfume.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgvk1krmeKBzqlV5bOD3tHJRWJCtBA1KA',
    appId: '1:140191368992:ios:c7f3920c8e0def8cd17945',
    messagingSenderId: '140191368992',
    projectId: 'ya-perfume',
    storageBucket: 'ya-perfume.firebasestorage.app',
    iosBundleId: 'com.famex.yaperfume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgvk1krmeKBzqlV5bOD3tHJRWJCtBA1KA',
    appId: '1:140191368992:ios:c7f3920c8e0def8cd17945',
    messagingSenderId: '140191368992',
    projectId: 'ya-perfume',
    storageBucket: 'ya-perfume.firebasestorage.app',
    iosBundleId: 'com.famex.yaperfume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG7VTiaAgG7ZUrGd9Mn9wiMbatwVUh2ZQ',
    appId: '1:140191368992:web:2ee1db1424912164d17945',
    messagingSenderId: '140191368992',
    projectId: 'ya-perfume',
    authDomain: 'ya-perfume.firebaseapp.com',
    storageBucket: 'ya-perfume.firebasestorage.app',
    measurementId: 'G-6QW75KJ625',
  );
}
